default_language_version:
    python: python3.10
fail_fast: true
repos:
-   repo: https://github.com/ambv/black
    rev: f6c139c
    hooks:
    -   id: black
        args: [--line-length=79]
        language_version: python3.10
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
        args: [--diff]
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    -   id: isort