version: '3'

services:
  web:
    build:
      context: .
    environment:
      - ENV_FILE_PATH
    volumes:
      - .:/code
    ports:
      - '4444:4444'
    expose:
      - '4444'
    restart: unless-stopped