version: '3'

services:
  web:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - '4444:4444'
    expose:
      - '4444'
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRES_DB=${DB_NAME:-db}
    volumes:
      - db-vol:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-vol:
